[project]
name = "build-flash-attention"
version = "0.1.0"
description = "Build flash-attn wheels"
requires-python = ">=3.12"
dependencies = [
    "ninja>=1.11.1.3",
    "numpy>=2.2.3",
    "packaging>=24.2",
    "pip>=25.0.1",
    "torch==2.11.0", # must match triton commit below
    "triton",
]

[tool.uv.sources]
triton = { git = "https://github.com/triton-lang/triton", rev = "9844da955a9db14ec69c9aac828ee9803085e288" }
