[project]
name = "build-flash-attention"
version = "0.1.0"
description = "Build flash-attn wheels"
requires-python = ">=3.12"
dependencies = [
    "ninja>=1.11.1.3",
    "numpy>=2.2.3",
    "packaging>=24.2",
    "pip>=25.0.1",
    "torch==2.14.0.dev20260618+cu130",
    "triton",
]

[tool.uv.sources]
triton = { git = "https://github.com/triton-lang/triton", rev = "5d6048aa0a324e090ada215b609ea76620133845" }
torch = { index = "torch-nightly-cu130" }

[[tool.uv.index]]
name = "torch-nightly-cu130"
url = "https://download.pytorch.org/whl/nightly/cu130"
explicit = true